import { Bar, Line } from "react-chartjs-2";
import { UNITS } from "../../constants/energy";
import { formatInt, formatNum } from "../../utils/formatters";
import { baseChartOptions, chartTheme } from "../../utils/chartOptions";
import { Section } from "../common/Section";
import { InfoTip } from "../common/InfoTip";
import { OperationalSummaryCard } from "./OperationalSummaryCard";

interface ForecastChartData {
  labels: string[];
  values: number[];
}

interface RiskHistogramData {
  labels: string[];
  counts: number[];
}

interface ModelMetrics {
  r2: number;
  mae: number;
  rmse: number;
  nTrain: number;
  nTest: number;
}

interface OperationalSummaryData {
  riskLevel: string;
  peakForecast: number;
  averageForecast: number;
  typicalZone: string;
  topFeature: string;
  recommendation: string;
}

interface ForecastRiskSectionProps {
  modelMetrics: ModelMetrics | null;
  forecast: ForecastChartData | null;
  histogram: RiskHistogramData | null;
  operationalSummary: OperationalSummaryData | null;
}

export function ForecastRiskSection({
  modelMetrics,
  forecast,
  histogram,
  operationalSummary,
}: ForecastRiskSectionProps) {
  return (
    <Section
      title="AI Forecasting & Risk Estimation"
      subtitle="Validated prediction metrics + short-horizon forecast + distribution risk"
    >
      {/* Model metrics row */}
      <div className="relative rounded-2xl border bg-white p-4 shadow-sm overflow-visible">
        <InfoTip title="Model Quality (Train/Test + Metrics)">
          <div className="space-y-2">
            <div>
              We split the sampled dataset into train/test (e.g., 75/25) and
              train a <b>Ridge Regression</b>.
            </div>
            <div className="rounded-lg bg-gray-50 p-2">
              Objective: <b>min</b> ||y − Xβ||² + <b>α</b>||β||²
            </div>
            <div>
              Metrics:
              <ul className="list-disc pl-5 mt-1 space-y-1">
                <li>
                  <b>R²</b>: how much variance is explained
                </li>
                <li>
                  <b>MAE</b>: average absolute error
                </li>
                <li>
                  <b>RMSE</b>: penalizes larger errors more
                </li>
              </ul>
            </div>
          </div>
        </InfoTip>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <div className="text-sm font-semibold text-gray-900">
              Predictive Model Quality
            </div>
            <div className="text-xs text-gray-500">
              Ridge regression with train/test split.
            </div>
          </div>

          {modelMetrics ? (
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-5 mr-20">
              {[
                { label: "Test R²", value: formatNum(modelMetrics.r2) },
                {
                  label: `MAE (${UNITS.energy})`,
                  value: formatNum(modelMetrics.mae),
                },
                {
                  label: `RMSE (${UNITS.energy})`,
                  value: formatNum(modelMetrics.rmse),
                },
                { label: "Train N", value: formatInt(modelMetrics.nTrain) },
                { label: "Test N", value: formatInt(modelMetrics.nTest) },
              ].map(({ label, value }) => (
                <div
                  key={label}
                  className="rounded-xl border bg-gray-50 px-3 py-2"
                >
                  <div className="text-[11px] text-gray-500">{label}</div>
                  <div className="text-sm font-semibold">{value}</div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-xs text-gray-500">
              No model metrics returned (summary.modelMetrics).
            </div>
          )}
        </div>
      </div>

      {/* Forecast + Histogram charts */}
      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        {/* Forecast */}
        <div className="relative rounded-2xl border bg-white p-4 shadow-sm overflow-visible">
          <InfoTip title="Short-Horizon Forecast (Demo Forecast)">
            <div className="space-y-2">
              <div>
                This chart shows <b>24 predicted steps</b> of Y (grid import)
                using the trained Ridge model.
              </div>
              <div className="rounded-lg bg-gray-50 p-2">
                Ŷ = β0 + β1X1 + β2X2 + β3X3 + β4X4 + β5X5
              </div>
              <div>
                Steps are generated by taking the last feature vector and
                applying small perturbations, then predicting Ŷ. (Not a full
                time-series model.)
              </div>
            </div>
          </InfoTip>

          <h3 className="text-sm font-semibold">Short-Horizon Forecast</h3>
          <div className="mt-3 h-[260px]">
            {forecast ? (
              <Line
                data={{
                  labels: forecast.labels,
                  datasets: [
                    {
                      label: `Predicted Y (Ŷ, ${UNITS.energy})`,
                      data: forecast.values,
                      tension: 0.25,
                      pointRadius: 2,
                      borderColor: chartTheme.forecast,
                      pointBackgroundColor: chartTheme.forecast,
                      backgroundColor: chartTheme.forecastSoft,
                      fill: true,
                    },
                  ],
                }}
                options={baseChartOptions(
                  "Step",
                  `Predicted Y (${UNITS.energy})`,
                )}
              />
            ) : (
              <div className="text-sm text-gray-500">
                No forecast returned (summary.forecast).
              </div>
            )}
          </div>
        </div>

        {/* Histogram */}
        <div className="relative rounded-2xl border bg-white p-4 shadow-sm overflow-visible">
          <InfoTip title="Risk Profile (Histogram of Y)">
            <div className="space-y-2">
              <div>
                A histogram summarizes the <b>distribution</b> of Y. We split
                [min(Y), max(Y)] into K bins.
              </div>
              <div className="rounded-lg bg-gray-50 p-2">
                count(bin i) = number of samples where aᵢ ≤ Y &lt; bᵢ
              </div>
              <div>
                Tall bars = typical operating range. Sparse/high bins indicate
                rare peak import (risk spikes).
              </div>
            </div>
          </InfoTip>

          <h3 className="text-sm font-semibold">Consumption Risk Profile</h3>
          <div className="mt-3 h-[260px]">
            {histogram ? (
              <Bar
                data={{
                  labels: histogram.labels,
                  datasets: [
                    {
                      label: "Frequency",
                      data: histogram.counts,
                      backgroundColor: chartTheme.accentSoft,
                      borderColor: chartTheme.accent,
                      borderWidth: 1,
                      borderRadius: 10,
                    },
                  ],
                }}
                options={baseChartOptions(
                  `Y bins (${UNITS.energy})`,
                  `Frequency (${UNITS.count})`,
                )}
              />
            ) : (
              <div className="text-sm text-gray-500">
                Load data to view chart.
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Operational summary card */}
      {operationalSummary && (
        <OperationalSummaryCard
          peakForecast={operationalSummary.peakForecast}
          avgForecast={operationalSummary.averageForecast}
          typicalZone={operationalSummary.typicalZone}
          topFeature={operationalSummary.topFeature}
          riskLevel={operationalSummary.riskLevel}
          recommendation={operationalSummary.recommendation}
        />
      )}
    </Section>
  );
}
